name: Deploy Quartz site to GitHub Pages
 
on:
  workflow_dispatch: # Permite activarlo manualmente
  schedule: 
    - cron: '0 3 * * *' # Ejecutar cada 3:00 UTC de cada dia, que es 6:00 de Argentina
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  chequeo:
    runs-on: ubuntu-22.04
    steps:
      - name: Get new commits
        run: echo "NEW_COMMIT_COUNT=$(git log --oneline --since '24 hours ago' | wc -l)" >> $GITHUB_ENV
      - name: Cat github env
        run: cat $GITHUB_ENV
      - name: Mostrar cantidad commits
        run: echo "$NEW_COMMIT_COUNT"

  build:
    needs: chequeo

    # if: ${{ env.NEW_COMMIT_COUNT > 0 }}
    runs-on: ubuntu-22.04
    steps:
      - name: Cat github env
        run: cat $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Building with docker
        uses: addnab/docker-run-action@v3
        with:
          image: juanbiancuzzo/obsidian-static-site:latest
          options: -v ${{ github.workspace }}:/usr/src/app/content
          run: sh -c ./start.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public
 
  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

